## Assignment Instructions


In [2]:
import numpy as np


Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \\ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \\ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \\ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \\ 18 & 84 \end{bmatrix} \end{bmatrix} $$

In [18]:
Tensor=np.array(
    [
        [[23,50],[7,12]],
        [[57,67],[99,43]],
        [[75,21],[57,12]],
        [[87,26],[18,84]]
    ]
)

In [19]:
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [20]:
Tensor.shape

(4, 2, 2)

* Lakukan perkalian terhadap matrix berikut:

$A = \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix}$  $B = \begin{bmatrix} 17 \\ 22 \\ 19 \end{bmatrix} $

In [22]:
A = np.array(
    [
        [23,50,9],
        [7,12,109],
        [57,67,98]
    ]
)

B = np.array([[17],[22],[19]])

In [23]:
#perkalian kedua matriks

#menggunakan Hadamar Product
print(A*B)

[[ 391  850  153]
 [ 154  264 2398]
 [1083 1273 1862]]


In [24]:
#menggunakan dot product
print(A@B)



[[1662]
 [2454]
 [4305]]


In [26]:
print(A.dot(B))

[[1662]
 [2454]
 [4305]]


* Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$A = \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} $$

In [27]:
A

array([[ 23,  50,   9],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [30]:
#Transpose Matriks
print("Transpose matriks A :")
print(A.T)

Transpose matriks A :
[[ 23   7  57]
 [ 50  12  67]
 [  9 109  98]]


In [31]:
#Determinan Matriks A
from numpy.linalg import det

print("Hasil determinan dari matriks A :")
print(det(A))

Hasil determinan dari matriks A :
133494.0


In [32]:
#Invers matriks A
print("Hasil inverse dari matriks A :")

print(np.linalg.inv(A))

Hasil inverse dari matriks A :
[[-0.04589719 -0.03218871  0.04001678]
 [ 0.04140261  0.01304178 -0.01830794]
 [-0.00161056  0.00980568 -0.00055433]]
