# Vector


In [ ]:
import numpy as np

## Pendefinisian List

1. Buatlah Vector dibawah ini dengan Python:
$$ \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$


In [ ]:
#pendefinisian vektor dengan menggunakan list
a = [17, 22, 19]
a = np.array(a)

In [ ]:
a

array([17, 22, 19])

2. Diberikan 3 buah vektor 3 dimensi: $$ A= \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} ,B= \begin{bmatrix} 10 \ 20 \ 11 \end{bmatrix}, C= \begin{bmatrix} 5 \ 12 \ 9 \end{bmatrix} $$
Hitunglah:

  A+B

  B-C

  A dot C

  A x B

  norm A

  Sudut antara vektor A dan B

  Buatlah plot dari vector berikut ini kedalam bidang 2D:

$$ U = \begin{bmatrix} 2 \ 5 \end{bmatrix}, V = \begin{bmatrix} 3 \ 1 \end{bmatrix} $$

In [ ]:
b  = [10,20, 12]
c = [5, 12, 9]

#Pendefinisian vektor dengan menggunakan numpy
b = np.array(b)
c = np.array(c)

#vektor hasil numpy dapat dilakukan operasi aritmatika     
#a+b
print("hasil pejumlahan vektor:")
print(a+b)

#b-c
print("hasil pengurangan vektor:")
print(b-c)

#a.b
print("hasil dot product :")
print(np.dot(a,b))

#norm A
print("hasil norm vektor a:")
print(np.linalg.norm(a))

hasil pejumlahan vektor:
[27 42 31]
hasil pengurangan vektor:
[5 8 3]
hasil dot product :
838
hasil norm vektor a:
33.67491648096547


In [ ]:
#cone similarity
result_dot_product = a.dot(b)
cos_theta = result_dot_product / (np.linalg.norm(a) * np.linalg.norm(b))

#mengubah cos_theta ke dalam radians untuk dicari derajat sudutnya
radians = np.arccos(cos_theta)

#mengubah radians untuk dicari derajat sudutnya
degree = np.degrees(radians)

print("cos theta              :", cos_theta)
print("radians                :", radians)
print("Degree/Derajat sudut   :", degree)



cos theta              : 0.9806060258555858
radians                : 0.19726625706719378
Degree/Derajat sudut   : 11.302523970292953


In [ ]:
# membuat plot dari 2 vector

u = np.array([2,5])
v = np.array([3,1])

In [ ]:
u

array([2, 5])

In [ ]:
v

array([3, 1])

In [ ]:
uni_vect = np.array([u,v])

In [ ]:
uni_vect

array([[2, 5],
       [3, 1]])

In [ ]:
uni_vect.shape

(2, 2)