**Objective**

* Basic understanding of eigen vector and value
* Able to finding eigen vector and value using Python
* Able to reconstruct a matrix using Python


In [1]:
import numpy as np
from numpy.linalg import eig


A = np.array([[1,2],[2,4]])
A

array([[1, 2],
       [2, 4]])

## mencari eigen vektor dan eigen value

In [2]:
eigval, eigvec =eig(A)

In [3]:
eigval

array([0., 5.])

In [4]:
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

## mencari akar

In [5]:
np.sqrt(125)

11.180339887498949

In [6]:
#mencari vektor unit
np.array([5,10]) / np.sqrt(125)

array([0.4472136 , 0.89442719])

In [7]:
#mengubah matrix ke bentuk semula
from numpy import diag
from numpy.linalg import eig,inv

B=eigvec.dot(diag(eigval)).dot(inv(eigvec))

In [8]:
B

array([[1., 2.],
       [2., 4.]])