## Membuat Vector

In [1]:
#membuat vektor 
a = [1,2,3,4,5]
b = [6,7,8,9,10]

a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

vektor dapat di definisikan dalam python dengan cara menggunakan list yang diubah menjadi array menggunakan library numpy

In [2]:
import numpy as np 

vect_a = np.array(a)
vect_b = np.array(b)

In [3]:
d = [6, 8]
vec_d = np.array(d)

##Euclidean distance (norm)

In [4]:
np.linalg.norm(vec_d, 2)

10.0

In [5]:
np.linalg.norm(vec_d, 1)

14.0

## Pengurangan vektor dengan skalar

In [6]:
vec_d - 10

array([-4, -2])

## Pengurangan vektor dengan vektor

In [22]:
vect_a = np.array([2,4,6])
vect_b = np.array([2,3,4])

vect_a - vect_b

array([0, 1, 2])

## Perkalian vektor dengan skalar

In [8]:
vect_a * 0.5

array([0.5, 1. , 1.5])

## Perkalian vektor dengan vektor

In [9]:
vect_a * vect_b 


array([ 2,  6, 12])

## Dot Product vektor, menahasilkan satu nilai

In [24]:
np.dot(vect_a,vect_b)

40

In [25]:
#save hasil do product
result_dot_product = vect_a@vect_b
result_dot_product

40

In [23]:
print(vect_a)
print(vect_b)

[2 4 6]
[2 3 4]


In [21]:
#vect_a = np.array([5,0])
#vect_b = np.array([8,0])

## Mencari apakah vektor mirip apa tidak menggunakan theta

In [26]:
cos_theta = result_dot_product / (np.linalg.norm(vect_a) * np.linalg.norm(vect_b))
cos_theta

0.9925833339709303