Carilah derivative/turunan dari sebuah fungsi:
 * $y = x^{2} + 2x + 1 \\ $ 
 * $y = 4x^{3} - 3x^{2} + 2x -1$

## Symbolic

In [2]:
#cara symbolic
import sympy as sy

x = sy.Symbol('x',real=True)

In [3]:
y1 = x**2+2*x+1

y1.diff(x)

2*x + 2

In [4]:
y2 = 4*x**3+3*x**2+2*x+1

y2.diff(x)

12*x**2 + 6*x + 2

## Numerik

 * $y = x^{2} + 2x + 1 \\ $ 


In [6]:
#cara 1
x = np.linspace(0,20)
y = x**2+2*x+1

df1 = np.diff(y)/np.diff(x)

df1

array([ 2.40816327,  3.2244898 ,  4.04081633,  4.85714286,  5.67346939,
        6.48979592,  7.30612245,  8.12244898,  8.93877551,  9.75510204,
       10.57142857, 11.3877551 , 12.20408163, 13.02040816, 13.83673469,
       14.65306122, 15.46938776, 16.28571429, 17.10204082, 17.91836735,
       18.73469388, 19.55102041, 20.36734694, 21.18367347, 22.        ,
       22.81632653, 23.63265306, 24.44897959, 25.26530612, 26.08163265,
       26.89795918, 27.71428571, 28.53061224, 29.34693878, 30.16326531,
       30.97959184, 31.79591837, 32.6122449 , 33.42857143, 34.24489796,
       35.06122449, 35.87755102, 36.69387755, 37.51020408, 38.32653061,
       39.14285714, 39.95918367, 40.7755102 , 41.59183673])

In [11]:
#cara2
x1 = np.linspace(0,20)
y1 = x1**2+2*x1+1

df2 = np.gradient(y1,x1)

In [12]:
df2

array([ 2.40816327,  2.81632653,  3.63265306,  4.44897959,  5.26530612,
        6.08163265,  6.89795918,  7.71428571,  8.53061224,  9.34693878,
       10.16326531, 10.97959184, 11.79591837, 12.6122449 , 13.42857143,
       14.24489796, 15.06122449, 15.87755102, 16.69387755, 17.51020408,
       18.32653061, 19.14285714, 19.95918367, 20.7755102 , 21.59183673,
       22.40816327, 23.2244898 , 24.04081633, 24.85714286, 25.67346939,
       26.48979592, 27.30612245, 28.12244898, 28.93877551, 29.75510204,
       30.57142857, 31.3877551 , 32.20408163, 33.02040816, 33.83673469,
       34.65306122, 35.46938776, 36.28571429, 37.10204082, 37.91836735,
       38.73469388, 39.55102041, 40.36734694, 41.18367347, 41.59183673])

 * $y = 4x^{3} - 3x^{2} + 2x -1$

In [10]:
#cara 1
x2 = np.linspace(0,20)
y2 = 4**3+3*x2**2+2*x2-1

df3 = np.diff(y2)/np.diff(x2)

df3

array([  3.2244898 ,   5.67346939,   8.12244898,  10.57142857,
        13.02040816,  15.46938776,  17.91836735,  20.36734694,
        22.81632653,  25.26530612,  27.71428571,  30.16326531,
        32.6122449 ,  35.06122449,  37.51020408,  39.95918367,
        42.40816327,  44.85714286,  47.30612245,  49.75510204,
        52.20408163,  54.65306122,  57.10204082,  59.55102041,
        62.        ,  64.44897959,  66.89795918,  69.34693878,
        71.79591837,  74.24489796,  76.69387755,  79.14285714,
        81.59183673,  84.04081633,  86.48979592,  88.93877551,
        91.3877551 ,  93.83673469,  96.28571429,  98.73469388,
       101.18367347, 103.63265306, 106.08163265, 108.53061224,
       110.97959184, 113.42857143, 115.87755102, 118.32653061,
       120.7755102 ])

In [14]:
#cara2
x3 = np.linspace(0,20)
y3 = 4**3+3*x3**2+2*x3-1

df4 = np.gradient(y3,x3)

df4

array([  3.2244898 ,   4.44897959,   6.89795918,   9.34693878,
        11.79591837,  14.24489796,  16.69387755,  19.14285714,
        21.59183673,  24.04081633,  26.48979592,  28.93877551,
        31.3877551 ,  33.83673469,  36.28571429,  38.73469388,
        41.18367347,  43.63265306,  46.08163265,  48.53061224,
        50.97959184,  53.42857143,  55.87755102,  58.32653061,
        60.7755102 ,  63.2244898 ,  65.67346939,  68.12244898,
        70.57142857,  73.02040816,  75.46938776,  77.91836735,
        80.36734694,  82.81632653,  85.26530612,  87.71428571,
        90.16326531,  92.6122449 ,  95.06122449,  97.51020408,
        99.95918367, 102.40816327, 104.85714286, 107.30612245,
       109.75510204, 112.20408163, 114.65306122, 117.10204082,
       119.55102041, 120.7755102 ])